# Generated by Django 4.2.16 on 2024-09-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='office_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialties',
            field=models.CharField(choices=[('Cleaning', 'Cleaning'), ('Filling', 'Filling'), ('Root Canal', 'Root Canal'), ('Crown', 'Crown'), ('Teeth Whitening', 'Teeth Whitening')], default='Teeth Whitening', max_length=50),
        ),
    ]
