# Generated by Django 4.2.16 on 2024-10-01 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_doctor_office_address_doctor_working_schedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_visit_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_visit_patients', to='management.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_appointment_patients', to='management.doctor'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_visit_procedures',
            field=models.ManyToManyField(blank=True, related_name='last_visit_procedures', to='management.procedure'),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment_procedure',
            field=models.ManyToManyField(blank=True, related_name='next_appointment_procedures', to='management.procedure'),
        ),
    ]
